### PR TITLE
Support for AIX platform

### PR DESCRIPTION
**Pull request by sh9189**
This PR builds on #84 and adds support for AIX platform. Our use-case is we have built omnibus packages for logrotate on AIX platform and would like to use that to rotate logs. This PR adds support so that logrotate can be installed from source and various options like logrotate package version can be configured through wrapper cookbook in the form of node attributes. Also fixes rubocop/foodcritic errors so that cookbook is up-to-date with latest rubocop/foodcritic

cc @johnbellone

### CODE REVIEW

**Comment by stevendanna** [comment]
Thanks, apologies I didn't get to #84 promptly, I'll take a look at this this week. Note that I don't have access to an AIX machine to test with currently.

**Comment by sh9189** [comment]
Thanks! Sure, there is nothing AIX specific though, it just adds support so that logrotate can also be installed from source and not just using package providers like Apt/Yum etc

**Comment by stevendanna** [comment]
This looks fine to me.  Based on the last few PRs I've gotten, it looks like I finally need to pay the cost of getting this cookbook up to date with modern testing practices.  :D

**Comment by stevendanna** [comment]
@sh9189 @johnbellone Hiya. This weekend, I'm getting the test suite up to date so I can do a 2.0 refactor and move from a definition to a resource for `logrotate_app`.  I know this is a bit of a pain but would you mind if I just cherry-picked the changes that adds the AIX support?  They might need to be massaged a bit, but I'll be sure to keep your authorship.  Alternatively, rebasing this without all of the testing changes would be helpful.

**Comment by stevendanna** [comment]
I cherry-picked one of your commits into the 2.0 branch.  If you don't mind taking a look, I'm happy to include other changes that are required to support your use case. You can see the ongoing work on 2.0 here:

https://github.com/stevendanna/logrotate/pull/89

I hope to merge that sometime this week after some additional testing.

**Comment by stevendanna** [comment]
Closing as the 2.0 branch is now merged.

**Pull request closed without merging**
