### PR TITLE
Fixing matcher and adding specs to verify

### PR DESCRIPTION
**Pull request by runwaldarshu**
Fixes https://github.com/stevendanna/logrotate/issues/71

### CODE REVIEW

**Comment by stevendanna** [comment]
Thanks! I'll take a look.  I'm hoping to avoid pulling berkshelf back in (it pulls in a lot of dependencies), I'll take a look at what we can do there.

**Comment by stevendanna** [comment]
I've included your tests in the 2.0 branch.  Since that branch converts the definition to the LWRP it uses a much smaller matcher.  You can see the ongoing work on 2.0 here:

https://github.com/stevendanna/logrotate/pull/89

I hope to merge that sometime this week after some additional testing.

**Comment by runwaldarshu** [comment]
Thanks for update @stevendanna

**Comment by stevendanna** [comment]
Closing as the 2.0 branch is merged.

**Pull request closed without merging**
