### PR TITLE
Fix typo in handle_options

### PR DESCRIPTION
**Pull request by smorgrav**
new_reosurce -> new_resource

### CODE REVIEW

**Comment by stevendanna** [comment]
Thanks for the PR.  I'll push this to the community site today.

**Comment by smorgrav** [comment]
No problem.

Some context from my side:

We get the logrotate dependency through the chef-client cookbook and only adjusts two attributes like this:

default['chef_client']['logrotate']['frequency'] = 'daily'
default['chef_client']['logrotate']['rotate'] = '12'

From what I see this (the frequency and rotate options)  is already covered with the rspecs?

So, what triggers this path?

**Comment by stevendanna** [comment]
@smorgrav Hrm, do you have the full stacktrace from the failure?

**Comment by smorgrav** [comment]
Recipe: chef-client::config
  * logrotate_app[chef-client] action enable

    ================================================================================
    Error executing action `enable` on resource 'logrotate_app[chef-client]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `new_reosurce' for Custom resource logrotate_app from cookbook logrotate

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/logrotate/resources/app.rb:106:in `handle_options'
    /var/chef/cache/cookbooks/logrotate/resources/app.rb:53:in `block in class_from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:122:in `instance_eval'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:122:in `compile_and_converge_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef-client/recipes/config.rb

     36:     logrotate_app 'chef-client' do
     37:       path [log_path]
     38:       rotate node['chef_client']['logrotate']['rotate']
     39:       frequency node['chef_client']['logrotate']['frequency']
     40:       options node['chef_client']['log_rotation']['options']
     41:       prerotate node['chef_client']['log_rotation']['prerotate']
     42:       postrotate node['chef_client']['log_rotation']['postrotate']
     43:       template_mode '0644'
     44:     end
     45:   end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef-client/recipes/config.rb:36:in `from_file'

    logrotate_app("chef-client") do
      action [:enable]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :logrotate_app
      cookbook_name "chef-client"
      recipe_name "config"
      path ["/var/log/chef/client.log"]
      rotate "12"
      frequency "daily"
      options "copytruncate"
      postrotate "/etc/init.d/chef-client reload >/dev/null || :"
      template_mode "0644"
      enable true
    end

**Comment by stevendanna** [comment]
It looks like something is setting `node['chef_client']['log_rotation']['options']` to "copytruncate".  The current default is an array: https://github.com/chef-cookbooks/chef-client/blob/master/attributes/default.rb#L184 but maybe it was different on the version of the chef-client cookbook you are on?

**Comment by smorgrav** [comment]
Looks like we are quite current:
  - chef-client (4.6.0)

**Comment by smorgrav** [comment]
Nah... we set it... I found this now:

chef.rb:default['chef_client']['log_rotation']['options'] = 'copytruncate'

Ok, that explains it I guess.

**Comment by stevendanna** [comment]
Test coverage for this added here: https://github.com/stevendanna/logrotate/commit/1668529dce4970490632710c4561048a978adc9a

**Pull request merged**
