### PR TITLE
Fix alignment when using multiple scripts

### PR DESCRIPTION
**Pull request by shoekstra**
Hi,

I noticed when using multiple scripts the alignment needed some fixing which PR handles.

Stephen

### CODE REVIEW

**Comment by shoekstra** [comment]
Fixed thd FC109 error by removing the provider param from `package`; I guess if people want to set some OS specific provider they can use `edit_resource`.

**Comment by shoekstra** [comment]
Hi @stevendanna - any update on this?

**Comment by stevendanna** [comment]
@shoekstra Apologies on this, I had planned to look at this package over my winter holiday but just failed to get to it.

Overall, I am +1 on the formatting changes, but I am hesitant to make a change to the API of this package.  We don't know if any users are currently using the provider param so removing it would be a breaking change for those users.  Perhaps we can add a foodcritic comment to ignore that violation for now and then mark this as a TODO for the next major release?

**Comment by shoekstra** [comment]
@stevendanna no problem, I'll update the PR to just include the format fix.

**Comment by shoekstra** [comment]
Hey @stevendanna, fix has been reverted and replaced with a TODO, added `FC109` to `.foodcritic` to make the tests green.  Hope that works!

**Comment by stevendanna** [comment]
Thanks!

**Pull request merged**
